stages:
  - deploy

build:
  stage: deploy
  image: gcr.io/k8s-skaffold/skaffold:latest
  script:
    - skaffold build --default-repo registry.usableapps.io/uenyioha/microservices-demo
  cache:
    key:
      files:
        - ~/.skaffold/cache
    paths:
      - ~/.skaffold/
  only:
    - main
