stages:
  - deploy

deploy:
  stage: deploy
  image: gcr.io/k8s-skaffold/skaffold:latest
  script:
    - skaffold run --default-repo localhost:32000 --port-forward --profile cluster

  only:
    - main
